### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by amiromayer** [6ag/shoppingCart#1]
Hi. Thnk you for sharing this awesome project. Can You also make it in English please? Thanks in advance

**Comment by 6ag** [comment]
Hi. You may be able to use Google translation.

**Comment by amiromayer** [comment]
Yeah thanks, and can you make it possible to just increment the number of good in ShoppingCartViewController, when I press "Add" button second, third etc times?

**Comment by 6ag** [comment]
Click the Add button, the button becomes disabled, can only add or subtract the number of commodities.

**Comment by amiromayer** [comment]
Can you make your project with storyboards? Not with the code?

**Comment by 6ag** [comment]
Of course, no problem. When I have free time use storyboards to write it again.

**Comment by amiromayer** [comment]
Thank you :) I will be waiting, please let me know

**Comment by 6ag** [comment]
OK.

**Comment by 6ag** [comment]
I used autolayou to layout, Do you have QQ number?

**Comment by amiromayer** [comment]
Unfortunately no :( but you can send the project to amir@ctrl.uz or upload to the dropbox and share the link. Thank you

**Comment by dinhjeffrey** [comment]
Hi, can I receive the autolayout version too? My email is dinhjeffreyy@gmail.com

**Comment by xuanInitial** [comment]
更改到swift3  现在是只能选择一件商品 然后tableview 不可以滚动了 其他商品 也不能购买     可以请教一下什么问题吗？
